name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  repository:
    description: 'Repository name (including owner)'
    default: github.action_repository	
  pull_request_id:
    description: 'Pull request ID'
    default: ${{ github.event.number }}

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: ../dist/index.js
  with:
    command: check_changelog
    repository: ${{ inputs.repository }}
    pull_request_id: ${{ inputs.pull_request_id }}