name: 'Record merged PRs on meta branch'
author: 'bd_'

# Add your action's branding here. This will appear on the GitHub Marketplace.
# branding:
#   icon: 'heart'
#   color: 'red'

# Define your inputs here.
inputs:
  repository:
    description: 'Repository name (including owner)'
    default: ${{ github.repository	}}
  pull_request_id:
    description: 'Pull request ID'
    default: ${{ github.event.number }}
  command:
    default: record_pr_changelog
  token:
    description: 'GitHub token'
    required: true
  git-committer:
    description: 'Git committer name'
    default: nadena.dev CI
  git-email:
    description: 'Git committer email'
    default: 'ci@nadena.dev'

# Define your outputs here.
# outputs:
#   time:
#     description: 'Your output description here'

runs:
  using: node20
  main: ../dist/index.js
